openapi: 3.0.1
info:
  description: OpenAPI
  title: OpenAPI
  version: 0.0.1
servers:
- url: /utilitatsfirmaapi/interna
- url: http://localhost:8080/utilitatsfirmaapi/interna
- url: https://dev.caib.es/utilitatsfirmaapi/interna
- url: https://proves.caib.es/utilitatsfirmaapi/interna
- url: https://se.caib.es/utilitatsfirmaapi/interna
- url: https://www.caib.es/utilitatsfirmaapi/interna
tags:
- description: Firma Validació Swagger v1.API Interna de utilitatsfirma que ofereix
    serveis de validació de firmes.
  name: SignatureValidation v1
paths:
  /secure/signaturevalidation/v1/validateSignature:
    post:
      operationId: validateSignature
      parameters:
      - description: Idioma en que s'han de retornar les dades i errors(Només suportat
          'ca' o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: languageUI
        required: false
        schema:
          default: ca
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateSignatureRequest'
        description: Operacio de firma simple en servidor d'un document
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: No Autenticat
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: No autoritzat
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateTypeMineturConstants'
          description: Error no controlat
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateSignatureResponse'
          description: Operació realitzada correctament
      security:
      - BasicAuth: []
      summary: Operacio de firma simple en servidor d'un document
      tags:
      - SignatureValidation v1
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    RestExceptionInfo:
      description: Estructura de dades utilitzada per passar informació d'un error
      example:
        field: field
        errorMessage: errorMessage
        stackTraceCause: stackTraceCause
        errorCode: 0
        stackTrace: stackTrace
      properties:
        errorCode:
          description: Codi intern de l'error. Si l'Aplicació no gestiona codis d'error
            llavors val null.
          format: int32
          type: integer
        errorMessage:
          description: Missatge de l'error
          type: string
        stackTrace:
          description: Stacktrace de l'excepció
          type: string
        stackTraceCause:
          description: Stacktrace de l'excepció causant de l'error si n'hi hagués.
          type: string
        field:
          description: Indica el camp en que hi ha un error de validació.
          type: string
      required:
      - errorMessage
      type: object
    ValidationStatusConstants:
      description: |
        Estats de la validació d'una firma:
            • "SIGNATURE_VALID"
            • "SIGNATURE_ERROR"
      enum:
      - 1
      - -1
      - -2
      format: int32
      type: integer
      x-enum-varnames:
      - SIGNATURE_VALID
      - SIGNATURE_ERROR
      - SIGNATURE_INVALID
      x-enum-descriptions:
      - ' '
      - ' '
      - ' '
    CertificateTypeEidasConstants:
      description: "* ESEAL: Certificado de sello electrónico. Pertenece a una persona\
        \ jurídica pero NO incluye un custodio.\n* ESIG: Certificado para firma electró\
        nica (persona física).\n* WSA: Certificado para autenticación de servidor\
        \ web.\r\n    public static final String EIDAS_UNKNOWN = \"UNKNOWN\"; // Se\
        \ desconoce el tipo del certificado\r\n                                  \
        \                        // (Se considera no cualificado a menos\r\n     \
        \                                                     // que se indique lo\
        \ contrario en\r\n                                                       \
        \   // certQualified)."
      enum:
      - ESEAL
      - ESIG
      - WSA
      - UNKNOWN
      type: string
      x-enum-varnames:
      - ESEAL
      - ESIG
      - WSA
      - UNKNOWN
      x-enum-descriptions:
      - ' '
      - ' '
      - ' '
      - ' '
    CertificateTypeMineturConstants:
      description: "Classificació del tipus de certificats:\r\nCLASSIFICACIO_DESCONEGUDA(-1;\r\
        \n\r\n                // 0 –Persona física-\r\n                CLASSIFICACIO_PERSONA_FISICA(0;\r\
        \n                // 1 –Persona jurídica (no cualificado)-\r\n           \
        \     CLASSIFICACIO_PERSONA_JURIDICA(1;\r\n                // 2 –No cualificados-\r\
        \n                CLASSIFICACIO_NO_QUALIFICATS(2;\r\n\r\n                //\
        \ 3 –Sede según la ley 40/2015(no cualificado)-\r\n                CLASSIFICACIO_SEU_ELECTRONICA(3;\r\
        \n                // 4 –Sello según la ley 40/2015(no cualificado)-\r\n  \
        \              CLASSIFICACIO_SEGELL(4;\r\n                // 5 –Empleado Pú\
        blico según la ley 40/2015-\r\n                CLASSIFICACIO_EMPLEAT_PUBLIC(5;\r\
        \n                // 6 –Entidad sin personalidad jurídica (no cualificado)-\r\
        \n                CLASSIFICACIO_ENTITAT_SENSE_PERSONALITAT_JURIDICA(6;\r\n\
        \                // 7 –Empleado público con seudónimo según el RD 1671/2009-\r\
        \n                CLASSIFICACIO_EMPLEAT_PUBLIC_AMB_PSEUDONIM(7;\r\n      \
        \          // 8 –Cualificado de sello, según el reglamente UE 910/2014-\r\n\
        \                CLASSIFICACIO_SEGELL_QUALIFICAT(8;\r\n                //\
        \ 9 –Cualificado de autenticación, según el reglamente UE 910/2014-\r\n  \
        \              CLASSIFICACIO_AUTENTIFICACIO_QUALIFICAT(9;\r\n            \
        \    // 10 –Cualificado de servicio cualificado de sello de tiempo-\r\n  \
        \              CLASSIFICACIO_SEGELL_DE_TEMPS(10;\r\n                // 11\
        \ –Persona física representante ante las Administraciones Públicas de persona\
        \ jurídica-\r\n                CLASSIFICACIO_AUTENTIFICACIO_REPRESENTANT_ADMINISTRACIO_PERSONA_JURIDICA(11;\r\
        \n                // 12 –Persona física representante ante las Administraciones\
        \ Públicas de entidad sin persona\r\n                // jurídica\r\n     \
        \           CLASSIFICACIO_AUTENTIFICACIO_REPRESENTANT_ADMINISTRACIO_ENTITAT(12;"
      enum:
      - -1
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      format: int32
      type: integer
      x-enum-varnames:
      - CLASSIFICACIO_DESCONEGUDA
      - CLASSIFICACIO_PERSONA_FISICA
      - |
        CLASSIFICACIO_PERSONA_JURIDICA
      - CLASSIFICACIO_NO_QUALIFICATS
      - CLASSIFICACIO_SEU_ELECTRONICA
      - CLASSIFICACIO_SEGELL
      - CLASSIFICACIO_EMPLEAT_PUBLIC
      - CLASSIFICACIO_ENTITAT_SENSE_PERSONALITAT_JURIDICA
      - CLASSIFICACIO_EMPLEAT_PUBLIC_AMB_PSEUDONIM
      - CLASSIFICACIO_SEGELL_QUALIFICAT
      - CLASSIFICACIO_AUTENTIFICACIO_QUALIFICAT
      - CLASSIFICACIO_SEGELL_DE_TEMPS
      - CLASSIFICACIO_AUTENTIFICACIO_REPRESENTANT_ADMINISTRACIO_PERSONA_JURIDICA
      - CLASSIFICACIO_AUTENTIFICACIO_REPRESENTANT_ADMINISTRACIO_ENTITAT
      x-enum-descriptions:
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    Document:
      description: Objecte que representa un Document/Fitxer
      example:
        data: data
        mime: mime
        name: name
      properties:
        name:
          description: Nom del fitxer.
          type: string
        mime:
          description: Tipus mime del fitxer.
          type: string
        data:
          description: Contingut del fitxer. En llistats aquest camp vendrà buit.
          format: byte
          type: string
      required:
      - name
      type: object
    SignatureRequestedInformation:
      example:
        returnCertificateInfo: true
        returnSignatureTypeFormatProfile: true
        validateCertificateRevocation: true
        returnValidationChecks: true
        returnCertificates: true
        returnTimeStampInfo: true
      properties:
        returnSignatureTypeFormatProfile:
          type: boolean
        validateCertificateRevocation:
          type: boolean
        returnCertificateInfo:
          type: boolean
        returnValidationChecks:
          type: boolean
        returnCertificates:
          type: boolean
        returnTimeStampInfo:
          type: boolean
      type: object
    ValidateSignatureRequest:
      example:
        detachedDocument:
          data: data
          mime: mime
          name: name
        signatureRequestedInformation:
          returnCertificateInfo: true
          returnSignatureTypeFormatProfile: true
          validateCertificateRevocation: true
          returnValidationChecks: true
          returnCertificates: true
          returnTimeStampInfo: true
        signatureDocument:
          data: data
          mime: mime
          name: name
      properties:
        detachedDocument:
          $ref: '#/components/schemas/Document'
        signatureDocument:
          $ref: '#/components/schemas/Document'
        signatureRequestedInformation:
          $ref: '#/components/schemas/SignatureRequestedInformation'
      type: object
    CertificateInformation:
      example:
        certificateDescription: certificateDescription
        administrationID: administrationID
        policyVersion: policyVersion
        country: country
        validSince: 2000-01-23T04:56:07.000+00:00
        subject: subject
        companyName: companyName
        keyUsageCertificateExtension: keyUsageCertificateExtension
        pseudonym: pseudonym
        organizationUnitName: organizationUnitName
        issuerOrganization: issuerOrganization
        certificateTypeMinetur: 5
        policyID: policyID
        entityName: entityName
        qcCompliance: qcCompliance
        europeanAdministrationID: europeanAdministrationID
        secondSurname: secondSurname
        keyUsageCertificate: keyUsageCertificate
        surnames: surnames
        cargo: cargo
        firstSurname: firstSurname
        email: email
        certificateQualified: true
        europeanOrganizationAdministrationID: europeanOrganizationAdministrationID
        policy: policy
        positionInTheCompany: positionInTheCompany
        serialNumber: serialNumber
        representationDocument: representationDocument
        systemOrComponentDescription: systemOrComponentDescription
        functionaryID: functionaryID
        fullName: fullName
        entityAdministrationID: entityAdministrationID
        birthDate: birthDate
        idlogOn: idlogOn
        firstName: firstName
        issuerID: issuerID
        domainName: domainName
        createdWithASecureDevice: true
        organization: organization
        validUntil: 2000-01-23T04:56:07.000+00:00
        organizationUnitID: organizationUnitID
        certificateTypeEidas: certificateTypeEidas
        qcSSCD: qcSSCD
        altresValors:
          key: altresValors
      properties:
        certificateDescription:
          type: string
        subject:
          type: string
        firstName:
          type: string
        firstSurname:
          type: string
        secondSurname:
          type: string
        surnames:
          type: string
        fullName:
          type: string
        administrationID:
          description: DNI del responsable del certificat
          type: string
        email:
          description: Email del responsable del certificat
          type: string
        birthDate:
          description: Data de naixement del responsable del certificat
          type: string
        pseudonym:
          description: "Pseudónimo del titular del certificat, si aplica. En certificats\
            \ de tipus 7 (Empleat Públic amb pseudònim) és obligatori"
          type: string
        representationDocument:
          description: "En certificats de Representació, indica el document que acredita\
            \ la representació del titular del certificat"
          type: string
        cargo:
          deprecated: true
          description: "Camp obsolet, es recomana usar positionInTheCompany"
          type: string
        positionInTheCompany:
          type: string
        domainName:
          description: "Domini del lloc web, tal y como figura en el Subject Alternative\
            \ Names"
          type: string
        systemOrComponentDescription:
          type: string
        europeanAdministrationID:
          description: "DNI o identificador europeu del responsable del certificat,\
            \ amb codificació estàndard segons ETSI EN 319 412"
          type: string
        europeanOrganizationAdministrationID:
          description: "NIF o identificador de l'organització europeu del responsable\
            \ del certificat, amb codificació estàndard segons ETSI EN 319 412"
          type: string
        functionaryID:
          type: string
        entityName:
          type: string
        entityAdministrationID:
          type: string
        certificateTypeMinetur:
          description: "El mapeo es realizado por el Ministerio de Hacienda y Administraciones\r\
            \nPúblicas e incluye a todos los prestadores de certificación reconocidos.Este\
            \ campo se devolverá para los certificados españoles, para facilitar el\
            \ tratamiento a aquellas aplicaciones que necesiten admitir tanto a certificados\
            \ españoles como europeos, ya que las siguientes clasificaciones son equivalentes:\n\
            \ * ESEAL => Clasificación = 8.\n * ESIG  => Clasificación = 0, 5, 7,\
            \ 11, 12.\n * WSA => Clasificación = 9.\n * UNKNOWN => Clasificación =\
            \ 2, 10.\nConsultar l'enumeració es.caib.portafib.apiinterna.client.signature.v1.model.CertificateTypeMineturConstants\
            \ per a més detalls."
          format: int32
          type: integer
        certificateTypeEidas:
          description: 'Consultar l''enumeració es.caib.portafib.apiinterna.client.signature.v1.model.CertificateTypeEidasConstants
            per a més detalls. '
          type: string
        certificateQualified:
          type: boolean
        createdWithASecureDevice:
          type: boolean
        issuerID:
          description: Nom de qui ha emès el certificat
          type: string
        issuerOrganization:
          description: Nom de l'organització emissora del certificat
          type: string
        companyName:
          type: string
        serialNumber:
          description: SerialNumber del certificat
          type: string
        keyUsageCertificate:
          type: string
        keyUsageCertificateExtension:
          type: string
        validSince:
          format: date-time
          type: string
        validUntil:
          format: date-time
          type: string
        policy:
          type: string
        policyVersion:
          type: string
        policyID:
          type: string
        country:
          type: string
        organization:
          type: string
        organizationUnitName:
          type: string
        organizationUnitID:
          type: string
        qcCompliance:
          type: string
        qcSSCD:
          type: string
        idlogOn:
          type: string
        altresValors:
          additionalProperties:
            type: string
          type: object
      type: object
    SignatureCheck:
      example:
        name: name
        type: type
      properties:
        name:
          type: string
        type:
          type: string
      type: object
    SignatureDetailInfo:
      example:
        indeterminateChecks:
        - name: name
          type: type
        - name: name
          type: type
        digestValue: digestValue
        validChecks:
        - name: name
          type: type
        - name: name
          type: type
        policyIdentifier: policyIdentifier
        timeStampInfo:
          certificateIssuer: certificateIssuer
          creationTime: 2000-01-23T04:56:07.000+00:00
          certificate:
          - certificate
          - certificate
          certificateSubject: certificateSubject
          algorithm: algorithm
        certificateChain:
        - - certificateChain
          - certificateChain
        - - certificateChain
          - certificateChain
        invalidChecks:
        - name: name
          type: type
        - name: name
          type: type
        signDate: 2000-01-23T04:56:07.000+00:00
        certificateInfo:
          certificateDescription: certificateDescription
          administrationID: administrationID
          policyVersion: policyVersion
          country: country
          validSince: 2000-01-23T04:56:07.000+00:00
          subject: subject
          companyName: companyName
          keyUsageCertificateExtension: keyUsageCertificateExtension
          pseudonym: pseudonym
          organizationUnitName: organizationUnitName
          issuerOrganization: issuerOrganization
          certificateTypeMinetur: 5
          policyID: policyID
          entityName: entityName
          qcCompliance: qcCompliance
          europeanAdministrationID: europeanAdministrationID
          secondSurname: secondSurname
          keyUsageCertificate: keyUsageCertificate
          surnames: surnames
          cargo: cargo
          firstSurname: firstSurname
          email: email
          certificateQualified: true
          europeanOrganizationAdministrationID: europeanOrganizationAdministrationID
          policy: policy
          positionInTheCompany: positionInTheCompany
          serialNumber: serialNumber
          representationDocument: representationDocument
          systemOrComponentDescription: systemOrComponentDescription
          functionaryID: functionaryID
          fullName: fullName
          entityAdministrationID: entityAdministrationID
          birthDate: birthDate
          idlogOn: idlogOn
          firstName: firstName
          issuerID: issuerID
          domainName: domainName
          createdWithASecureDevice: true
          organization: organization
          validUntil: 2000-01-23T04:56:07.000+00:00
          organizationUnitID: organizationUnitID
          certificateTypeEidas: certificateTypeEidas
          qcSSCD: qcSSCD
          altresValors:
            key: altresValors
        algorithm: algorithm
      properties:
        algorithm:
          type: string
        digestValue:
          type: string
        signDate:
          format: date-time
          type: string
        validChecks:
          items:
            $ref: '#/components/schemas/SignatureCheck'
          type: array
        invalidChecks:
          items:
            $ref: '#/components/schemas/SignatureCheck'
          type: array
        indeterminateChecks:
          items:
            $ref: '#/components/schemas/SignatureCheck'
          type: array
        policyIdentifier:
          type: string
        certificateInfo:
          $ref: '#/components/schemas/CertificateInformation'
        certificateChain:
          items:
            items:
              format: byte
              type: string
            type: array
          type: array
        timeStampInfo:
          $ref: '#/components/schemas/TimeStampInfo'
      type: object
    TimeStampInfo:
      example:
        certificateIssuer: certificateIssuer
        creationTime: 2000-01-23T04:56:07.000+00:00
        certificate:
        - certificate
        - certificate
        certificateSubject: certificateSubject
        algorithm: algorithm
      properties:
        creationTime:
          format: date-time
          type: string
        certificateIssuer:
          type: string
        certificateSubject:
          type: string
        certificate:
          items:
            format: byte
            type: string
          type: array
        algorithm:
          type: string
      type: object
    ValidateSignatureResponse:
      example:
        signProfile: signProfile
        signType: signType
        signMode: 1
        validationStatus:
          errorException: errorException
          status: 5
          errorMsg: errorMsg
        signatureDetailInfo:
        - indeterminateChecks:
          - name: name
            type: type
          - name: name
            type: type
          digestValue: digestValue
          validChecks:
          - name: name
            type: type
          - name: name
            type: type
          policyIdentifier: policyIdentifier
          timeStampInfo:
            certificateIssuer: certificateIssuer
            creationTime: 2000-01-23T04:56:07.000+00:00
            certificate:
            - certificate
            - certificate
            certificateSubject: certificateSubject
            algorithm: algorithm
          certificateChain:
          - - certificateChain
            - certificateChain
          - - certificateChain
            - certificateChain
          invalidChecks:
          - name: name
            type: type
          - name: name
            type: type
          signDate: 2000-01-23T04:56:07.000+00:00
          certificateInfo:
            certificateDescription: certificateDescription
            administrationID: administrationID
            policyVersion: policyVersion
            country: country
            validSince: 2000-01-23T04:56:07.000+00:00
            subject: subject
            companyName: companyName
            keyUsageCertificateExtension: keyUsageCertificateExtension
            pseudonym: pseudonym
            organizationUnitName: organizationUnitName
            issuerOrganization: issuerOrganization
            certificateTypeMinetur: 5
            policyID: policyID
            entityName: entityName
            qcCompliance: qcCompliance
            europeanAdministrationID: europeanAdministrationID
            secondSurname: secondSurname
            keyUsageCertificate: keyUsageCertificate
            surnames: surnames
            cargo: cargo
            firstSurname: firstSurname
            email: email
            certificateQualified: true
            europeanOrganizationAdministrationID: europeanOrganizationAdministrationID
            policy: policy
            positionInTheCompany: positionInTheCompany
            serialNumber: serialNumber
            representationDocument: representationDocument
            systemOrComponentDescription: systemOrComponentDescription
            functionaryID: functionaryID
            fullName: fullName
            entityAdministrationID: entityAdministrationID
            birthDate: birthDate
            idlogOn: idlogOn
            firstName: firstName
            issuerID: issuerID
            domainName: domainName
            createdWithASecureDevice: true
            organization: organization
            validUntil: 2000-01-23T04:56:07.000+00:00
            organizationUnitID: organizationUnitID
            certificateTypeEidas: certificateTypeEidas
            qcSSCD: qcSSCD
            altresValors:
              key: altresValors
          algorithm: algorithm
        - indeterminateChecks:
          - name: name
            type: type
          - name: name
            type: type
          digestValue: digestValue
          validChecks:
          - name: name
            type: type
          - name: name
            type: type
          policyIdentifier: policyIdentifier
          timeStampInfo:
            certificateIssuer: certificateIssuer
            creationTime: 2000-01-23T04:56:07.000+00:00
            certificate:
            - certificate
            - certificate
            certificateSubject: certificateSubject
            algorithm: algorithm
          certificateChain:
          - - certificateChain
            - certificateChain
          - - certificateChain
            - certificateChain
          invalidChecks:
          - name: name
            type: type
          - name: name
            type: type
          signDate: 2000-01-23T04:56:07.000+00:00
          certificateInfo:
            certificateDescription: certificateDescription
            administrationID: administrationID
            policyVersion: policyVersion
            country: country
            validSince: 2000-01-23T04:56:07.000+00:00
            subject: subject
            companyName: companyName
            keyUsageCertificateExtension: keyUsageCertificateExtension
            pseudonym: pseudonym
            organizationUnitName: organizationUnitName
            issuerOrganization: issuerOrganization
            certificateTypeMinetur: 5
            policyID: policyID
            entityName: entityName
            qcCompliance: qcCompliance
            europeanAdministrationID: europeanAdministrationID
            secondSurname: secondSurname
            keyUsageCertificate: keyUsageCertificate
            surnames: surnames
            cargo: cargo
            firstSurname: firstSurname
            email: email
            certificateQualified: true
            europeanOrganizationAdministrationID: europeanOrganizationAdministrationID
            policy: policy
            positionInTheCompany: positionInTheCompany
            serialNumber: serialNumber
            representationDocument: representationDocument
            systemOrComponentDescription: systemOrComponentDescription
            functionaryID: functionaryID
            fullName: fullName
            entityAdministrationID: entityAdministrationID
            birthDate: birthDate
            idlogOn: idlogOn
            firstName: firstName
            issuerID: issuerID
            domainName: domainName
            createdWithASecureDevice: true
            organization: organization
            validUntil: 2000-01-23T04:56:07.000+00:00
            organizationUnitID: organizationUnitID
            certificateTypeEidas: certificateTypeEidas
            qcSSCD: qcSSCD
            altresValors:
              key: altresValors
          algorithm: algorithm
      properties:
        signType:
          type: string
        signMode:
          format: int32
          type: integer
        signProfile:
          type: string
        validationStatus:
          $ref: '#/components/schemas/ValidationStatus'
        signatureDetailInfo:
          items:
            $ref: '#/components/schemas/SignatureDetailInfo'
          type: array
      type: object
    ValidationStatus:
      example:
        errorException: errorException
        status: 5
        errorMsg: errorMsg
      properties:
        status:
          format: int32
          type: integer
        errorMsg:
          type: string
        errorException:
          type: string
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http

